config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: 'pastels#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]

  resources :pastels

  # resources :reviews, only: [:new, :create]

  resources :orders, except: [:index] do
    member do
      get :review
    end
  end

  # get 'orders/:id/confirm_order', to: "orders#confirm_order", as: :confirm_order


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :pastel
  belongs_to :user

  validates :quantity, presence: true
  validates :order_date, presence: true
end

app/models/pastel.rb
class Pastel < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_name_address_description,
    against: [ :name, :address, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pastels, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit


  after_action :verify_authorized, :except => :index, unless: :devise_controller?
  after_action :verify_policy_scoped, :only => :index, unless: :devise_controller?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :review]

  def show
    authorize @order
  end

  def new
    @order = Order.new
     authorize @order
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @pastel = @order.pastel
    authorize @order

    if @order.quantity > @pastel.stock
      redirect_to pastel_path(@pastel)
      flash[:alert] = "Not enough stock"
    elsif @order.save
      @pastel.stock -= @order.quantity
      @pastel.save!
      redirect_to user_path(current_user)
    else
      render :new
      # needs to be changed when we have a pastel show page
    end
  end

  def edit
    authorize @order
  end

  def update
    @pastel = @order.pastel
    authorize @order
    if @order.quantity > @pastel.stock
      flash[:alert] = "Not enough stock, please try again"
    elsif @order.update(order_params)
      redirect_to order_path(@order)
    else
      render :edit # print edit.html.erb
    end
  end

  def destroy
    authorize @order
    @order.destroy
    redirect_to user_path
  end

  def review
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:pastel_id, :user_id, :quantity, :order_date, :review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pastels_controller.rb
class PastelsController < ApplicationController
  before_action :set_pastel, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @order = Order.new
    @pastels = policy_scope(Pastel)

    @pastels = Pastel.geocoded

    if params[:query].present?
      @pastels = Pastel.search_by_name_address_description(params[:query])
    end

    @markers = @pastels.map do |pastel|
      {
        lat: pastel.latitude,
        lng: pastel.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pastel: pastel })
      }
    end
  end

  def show
    authorize @pastel
    @order = Order.new
  end

  def new
    @pastel = Pastel.new
    authorize @pastel
  end

  def create
    @pastel = Pastel.new(pastel_params)
    @pastel.user = current_user
    authorize @pastel

    if @pastel.save
      redirect_to pastels_path
    else
      render :new
    end
  end

  def edit
    authorize @pastel
  end

  def update
    authorize @pastel
    if @pastel.update(pastel_params)
      redirect_to pastel_path(@pastel)
    else
      render :edit # print edit.html.erb
    end
  end

  def destroy
    authorize @pastel
    @pastel.destroy
  end

  private

  def set_pastel
    @pastel = Pastel.find(params[:id])
  end

  def pastel_params
    params.require(:pastel).permit(:name, :description, :price, :stock, :photo, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
    @my_pastels = Pastel.where(user_id: @user.id)
    @orders_placed = Order.where(user_id: @user.id)
    @orders_received = Order.where(pastel_id: @my_pastels)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Pastels</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  <!-- Flatpickr stylesheet -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  <!-- <link rel="stylesheet" href="https://npmcdn.com/flatpickr/dist/themes/dark.css"> -->

</head>
<body>
  <% if (user_signed_in?) then %>
    <%= render 'shared/navbar' %>
  <% end %>

  <%= render 'shared/flashes' %>

  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->

  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

</body>
</html>

app/views/orders/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <h2 class="text-center">What would you like to change in your order</h2>
      <%= simple_form_for @order do |f| %>
        <%= f.input :quantity, input_html: { min: '0', max: "#{@order.pastel.stock}" }%>
        <%= f.input :order_date %>
        <div class="text-center">
          <%= f.submit class:'btn btn-outline-secondary' %>
          <%= link_to 'Cancel', order_path(@order), class: 'btn btn-outline-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/review.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <h2>Yay! Your pastel is on the way...🏃🏽‍♂️</h2>

      <p>Please leave a review</p>
      <%= simple_form_for @order do |f| %>
        <%= f.input :review %>
        <%= f.button :submit, "Add a review", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <h2 class="mb-3 text-center">You're almost there...here is your order</h2>
      <table class="table">
        <thead>
          <th scope="col">Pastel</th>
          <th scope="col">Qty</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @order.pastel.name %></td>
            <td><%= @order.quantity %></td>
          </tr>
          <tr>
            <td>Total: € <%= @order.pastel.price * @order.quantity %></td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to 'Delete Order', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
        <%= link_to 'Update Order', edit_order_path(@order), class: 'btn btn-outline-secondary btn-sm' %>
        <% disabled_button = @order.review.nil? ? "" : "disabled" %>
        <% if DateTime.now > @order.order_date %>
        <%= link_to 'Review', review_order_path(@order), {'data-toggle' =>  "modal", 'data-target' => '#reviewModalCenter', class: "btn btn-sm btn-success #{disabled_button}", id: "reviewButton"} %>
        <% else %>
        <%= link_to 'Review', review_order_path(@order), {'data-toggle' =>  "modal", 'data-target' => '#reviewModalCenter', class: 'btn btn-light disabled'} %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- modal -->

<div class="modal fade" id="reviewModalCenter" tabindex="-1" role="dialog" aria-labelledby="reviewModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reviewModalLongTitle">Please review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @order do |f| %>
        <%= f.input :review %>
        <div class="d-flex justify-content-between">
          <%= f.button :submit, "Add a review", class: 'btn btn-success', id: '#reviewSubmitButton' %>
          <%= f.button :button, 'Cancel', :type => 'reset', class: "btn btn-outline-secondary mb-2", data: { toggle: "modal", target: "#reviewModalCenter" } =%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Welcome To Pastel</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pastels/_info_window.html.erb
<h2><%= pastel.name %></h2>
<p><%= pastel.address %></p>

app/views/pastels/create.html.erb
<h1>Pastels#create</h1>
<p>Find me in app/views/pastels/create.html.erb</p>

app/views/pastels/destroy.html.erb
<h2>Destroy pastel</h2>
<%= render 'show' %>

app/views/pastels/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <h2>Edit <%= @pastel.name %></h2>
      <%= render 'shared/pastel_form' %>
    </div>
  </div>
</div>

app/views/pastels/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.9)), url(https://images.unsplash.com/photo-1533421821268-87e42c1d70b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1078&q=80);">
  <div class="text-center">
    <h1>Meus Pastels</h1>
    <p>Eat a pastel. Change your life.</p>
  </div>
</div>

<div class="main-container">
  <div class="pastel-section col-8">

    <!-- Search -->
    <% if params[:query].present? %>
      <h1 class="text-center">Search Results</h1>
    <% end %>

    <div class="row d-flex justify-content-center card-section">
      <div class="cards bg-white">
        <% @pastels.each do |pastel| %>
        <div class="card card-shadow m-2" style="max-width: 18rem;">
          <%= link_to pastel, class: 'btn' do %>
          <%= cl_image_tag pastel.photo, class: 'card-img-top' %>
          <% end %>

          <!-- Review Modal button -->
          <span>
            <button type="button" class="badge badge-primary btn-review" data-toggle="modal" data-target="#reviewModalCenter-<%= pastel.id %>">
            <i class="fas fa-comments"></i> <p> Reviews! </p></button>
          </span>

          <!-- End of Review Modal Button -->

          <!-- Review Modal -->

          <div class="modal fade" id="reviewModalCenter-<%= pastel.id %>" tabindex="-1" role="dialog" aria-labelledby="reviewModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="reviewModalLongTitle"><%= pastel.name %> Reviews</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <% pastel.orders.each do |order| %>
                    <div class="card-product">
                      <i class="fas fa-quote-left"></i>
                      <i class="fas fa-quote-right"></i>

                      <img class="avatar ml-2" src="https://kitt.lewagon.com/placeholder/users/papillard" />

                      <div>
                        <h2 class="text-muted ml-4"><%= order.review %></h2>

                        <p class="ml-4 mb-0">-<em><%= order.user.first_name %></em>-</p>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <!-- End of Review Modal -->

          <div class="card-body">
            <h5 class="card-title"><%= pastel.name %></h5>
            <p class="card-text"><%= pastel.description %></p>
            <p class="card-text"><%= pastel.stock %> pastels available</p>
          </div>

          <div class="d-flex justify-content-between align-items-center m-2">

            <!-- Order modal button -->

            <!-- disable order button if stock below 0-->
            <% if pastel.stock <= 0 %>
              <%= link_to new_order_path, {'data-toggle' =>  "modal", 'data-target' => "#orderModalCenter-#{pastel.id}", class: 'btn btn-success disabled'} do %>
              <i class="fas fa-plus mr-1"></i>Order
              <% end %>

            <% else %>
              <%= link_to new_order_path, {'data-toggle' =>  "modal", 'data-target' => "#orderModalCenter-#{pastel.id}", class: 'btn btn-success'} do %>
              <i class="fas fa-plus mr-1"></i>Order
              <% end %>
            <% end %>

            <!-- End of Order modal button -->

            <!-- Order Modal -->
            <div class="modal fade" id="orderModalCenter-<%= pastel.id %>" tabindex="-1" role="dialog" aria-labelledby="orderModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="orderModalLongTitle">Please confirm quantity and delivery date</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">

                    <%= simple_form_for @order, validate: true do |f| %>
                    <%= f.input :quantity, validate: { min: '0', max: "#{pastel.stock}" } %>
                    <%= f.input :order_date, as: :string, input_html: { class: 'flatpickr-input'} %>
                    <%= f.input :pastel_id, as: :hidden, :input_html => { value: pastel.id } %>
                    <div class="d-flex justify-content-between">
                      <%= f.submit class: 'btn btn-primary' %>
                      <%= f.button :button, 'Cancel', :type => 'reset', class: "btn btn-outline-secondary", data: { dismiss: "modal", target: "orderModalCenter-#{pastel.id}" } %>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

            <!-- End of Order modal -->
            <p class="card-text float-right">€ <%= pastel.price %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div
  id="map" class="col-4"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

<!-- Footer -->

<div class="footer d-flex justify-content-center align-items-center">
    <p>MeusPastels was made with <i class="fas fa-coffee"></i> at Le Wagon</p>
</div>

app/views/pastels/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-5 form">
      <h2>Let's add a new pastel</h2>
      <%= render 'shared/pastel_form' %>
    </div>
  </div>
</div>

app/views/pastels/pastels_user.html.erb
<% @users_pastel = @pastel.find_by(current_user) %>
<div class="container">
  <h1 class="text-center">Welcome to Pastels</h1>
  <div class="row d-flex justify-content-center">
    <div class="cards">
      <% @users_pastels.each do |pastel| %>
      <div class="card m-2" style="width: 18rem;">
        <%= link_to pastel, class: 'btn' do %>
        <img class="card-img-top" src="https://source.unsplash.com/1600x900/?pastel-de-nata" alt="Card image cap">
        <% end %>
        <div class="card-body">
          <!-- <h5 class="card-title"><%= pastel.name %></h5> -->
          <div class="d-flex justify-content-between">
            <p class="card-text"><%= pastel.description %></p>
            <p class="card-text float-right">€ <%= pastel.price %></p>
          </div>
        </div>
        <div class="d-flex justify-content-between align-items-center m-2">
          <%= link_to 'Details', pastel, class: 'btn btn-outline-secondary' %>
          <!-- modal button -->
          <%= link_to pastel_path(pastel),  {'data-toggle' =>  "modal", 'data-target' => '#orderModalCenter', class: 'btn btn-sm btn-outline-secondary my-0'} do %>
          <i class="fas fa-plus mr-1"></i>Order me!
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="orderModalCenter" tabindex="-1" role="dialog" aria-labelledby="orderModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLongTitle">Here is your order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        this is an order...
      </div>
    </div>
  </div>
</div>

app/views/pastels/show.html.erb
<div class="row justify-content-center">
  <div class="col-6 text-center">
    <%= cl_image_tag @pastel.photo, {:size => "360x280", :crop=>"fill"} %>
    <h2><%= @pastel.name %></h2>
    <p>Description: <%= @pastel.description %></p>
    <p>Price: € <%= @pastel.price %></p>
    <p>Available: <%= @pastel.stock %></p>
    <% if policy(@pastel).destroy? %>
    <%= link_to 'Remove', pastel_path(@pastel), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <% end %>
    <% if policy(@pastel).edit? %>
    <%= link_to 'Edit', edit_pastel_path(@pastel), class: 'btn btn-outline-secondary' %>
    <% end %>


  </div>
</div>

app/views/pastels/update.html.erb
<h1>Pastels update done</h1>
<p><%= link_to 'Go back', pastel_path(@pastel), class: 'btn btn-outline-secondary btn-sm' %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_pastel_form.html.erb
<%= simple_form_for @pastel, validate: true do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.input :stock %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="d-flex justify-content-between">
    <%= f.submit class: 'btn btn-primary mb-2' %>
    <%= link_to 'Cancel', pastels_path, class: 'btn btn-outline-secondary mb-2' %>
  </div>
<% end %>

app/views/users/show.html.erb
<!-- User Dashboard -->


<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <i class="fas fa-caret-down"></i> Profile
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %><br>
        <label>Name:</label> <%= "#{@user.first_name} #{@user.last_name}" %><br>
        <label>Email:</label> <%= @user.email %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <i class="fas fa-caret-down"></i> Orders placed
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">

          <% @orders_placed.each do |order| %>

            <div class="card">
              <h5 class="card-header">Order #<%= order.id %></h5>
              <div class="card-body">
                <h5 class="card-title">Pastel: <%= order.pastel.name%></h5>
                <p class="card-text">
                  <label>Order created at:</label> <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %><br>
                  <label>Quantity:</label> <%= order.quantity %><br>
                  <label>Price:</label> <%= order.pastel.price %><br>
                </p>
                <%= link_to "Delete", order_path(order.id), method: :delete, confirm: "Positive?", title: "Delete", class:"btn btn-danger" %>
              </div>
            </div>
            <br>
          <% end %>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <i class="fas fa-caret-down"></i> Orders received
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">

          <% @orders_received.each do |order| %>

            <div class="card">
              <h5 class="card-header">Order #<%= order.id %></h5>
              <div class="card-body">
                <h5 class="card-title">Pastel: <%= order.pastel.name%></h5>
                <p class="card-text">
                  <label>Order created at:</label> <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %><br>
                  <label>Quantity:</label> <%= order.quantity %><br>
                  <label>Price:</label> <%= order.pastel.price %><br>
                  <label>Buyer:</label> <%= order.user.first_name %> <%= order.user.last_name %><br>
                </p>
              </div>
            </div>
            <br>
          <% end %>

      </div>
    </div>
  </div>


  <div class="card">
    <div class="card-header" id="headingFour">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          <i class="fas fa-caret-down"></i> Pastels
        </button>
      </h2>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
      <div class="card-body">
        <%= link_to "Add a pastel", new_pastel_path, class: "btn btn-primary" %>
        <div class="row d-flex justify-content-center card-section">
          <div class="cards bg-white">
            <% @my_pastels.each do |pastel| %>
            <div class="card card-shadow m-2" style="max-width: 18rem;">
              <%= link_to pastel, class: 'btn' do %>
              <%= cl_image_tag pastel.photo, class: 'card-img-top' %>
              <% end %>

              <!-- Review Modal button -->
              <span>
                <button type="button" class="badge badge-primary btn-review" data-toggle="modal" data-target="#reviewModalCenter-<%= pastel.id %>">
                <i class="fas fa-comments"></i> <p> Reviews! </p></button>
              </span>

              <!-- End of Review Modal Button -->

              <!-- Review Modal -->

              <div class="modal fade" id="reviewModalCenter-<%= pastel.id %>" tabindex="-1" role="dialog" aria-labelledby="reviewModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="reviewModalLongTitle"><%= pastel.name %> Reviews</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <% pastel.orders.each do |order| %>
                        <div class="card-product">
                          <i class="fas fa-quote-left"></i>
                          <i class="fas fa-quote-right"></i>

                          <img class="avatar ml-2" src="https://kitt.lewagon.com/placeholder/users/papillard" />

                          <div>
                            <h2 class="text-muted ml-4"><%= order.review %></h2>

                            <p class="ml-4 mb-0">-<em><%= order.user.first_name %></em>-</p>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

              <!-- End of Review Modal -->

              <div class="card-body">
                <h5 class="card-title"><%= pastel.name %></h5>
                <p class="card-text"><%= pastel.description %></p>
                <p class="card-text"><%= pastel.stock %> pastels available</p>
              </div>

              <div class="d-flex justify-content-between align-items-center m-2">
                <p></p>
                <p class="card-text float-right">€ <%= pastel.price %></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>





<!-- Modal -->
<div class="modal fade" id="orderModalCenter" tabindex="-1" role="dialog" aria-labelledby="orderModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLongTitle">Here is your order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        this is an order...
      </div>
    </div>
  </div>
</div>